trigger:
  branches:
    include:
      - main

variables:
- group: StaticWebSecrets

stages:
- stage: Build
  displayName: Build Static App
  jobs:
    - job: BuildJob
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: AzureStaticWebApp@0
          inputs:
            app_location: '.'
            output_location: '.'
            azure_static_web_apps_api_token: $(deployment_token)
