
trigger:
  branches:
    include:
      - main

variables:
  azure_static_web_apps_api_token: $(deployment_token)

stages:
  - stage: Build
    displayName: Build Static App
    jobs:
      - job: BuildJob
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '.'                 # Your app root folder (where index.html is)
              output_location: '.'              # Same if no build step (React = 'build', Angular = 'dist', etc.)
              azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
